### ISSUE TITLE
looking for license information

### ISSUE THREAD

**Issue by anapsix** [mvilche/go-tasks#1]
Thank you for making `go-tasks`, Martin!
It's very handy for running cron tasks as unprivileged user, especially in container environment.
I've processed the binary with `upx --ultra-brute go-tasks`, which reduced it's size to 3.5MB, and would like to include it in my project's repo (acknowledging it's origin). But I did not find a license selected for `go-tasks` project.

Please add a LICENSE to your repo (see https://choosealicense.com for inspiration),

**Comment by mvilche** [comment]
Hi.
Thank you for using my project.
It is a very good utility combined with openshift for the execution of scheduled tasks
You can contact me if you have problems or questions about it.
I will add the license shortly

**Comment by mvilche** [comment]
If you want deploy in openshift or kubernetes, you can use the template https://github.com/mvilche/crond-noroot

**Comment by anapsix** [comment]
yep, I found that first.. but I'm integrating it into the docker image (deployed to K8s with included Helm chart), which retrieves logs on schedule, so it's helpful to use a cron-like scheduler, to avoid having to deal with overlaps of time ranges when requesting logs.

See https://github.com/anapsix/get-cloudflare-logs

**Comment by mvilche** [comment]
#1 fixed
MIT license added.

Great, at your service.
See you

**Comment by anapsix** [comment]
thank you Martin!!
